### ISSUE TITLE
¿Qué es c_n?

### ISSUE THREAD

**Issue by Erasmo98** [lbenet/2021-2_TSelecFisComp-1#14]
En el segundo problema de la segunda tarea se comienza definiendo c_n como el valor de c donde ocurre un ciclo súper estable de periodo 2^n:

https://github.com/lbenet/2021-2_TSelecFisComp-1/blob/015a0b31a8df18dbc2956e0fb7b7896a77803de4/tareas/Tarea2.jl#L27

Sin embargo, más adelante más adelante se menciona que c_n es el valor de c donde ocurre una bifurcación de doblamiento de periodo, lo cual contradice la definición original de c_n:

https://github.com/lbenet/2021-2_TSelecFisComp-1/blob/015a0b31a8df18dbc2956e0fb7b7896a77803de4/tareas/Tarea2.jl#L31

Y finalmente se mencionan algunos de los primeros valores de c_n. Resulta ser que dichos valores corresponden a bifurcaciones pero no sólo de doblamiento de periodo sino también de silla nodo:

https://github.com/lbenet/2021-2_TSelecFisComp-1/blob/015a0b31a8df18dbc2956e0fb7b7896a77803de4/tareas/Tarea2.jl#L34

No sé si lo anterior lo escribí correctamente. Lo que sí es que estoy confundido, ¿qué es c_n? Si es el valor de c donde ocurre un ciclo súper estable el cálculo y el valor de c_n es distinto que cuando ocurre una bifurcación. Más bien entiendo que es cuando ocurre una bifurcación pero, ¿de qué tipo de bifurcación? Si sólo es de doblamiento de periodo, sí sé cómo hacer el cálculo. Si también considerando bifurcaciones de silla nodo, no tengo muy claro cómo sería.

**Comment by lbenet** [comment]
Gracias por el comentario. 

La sugerencia es usar la primera definición, es decir, que c_n corresponde al valor de c cuando se tiene una órbita superestable de periodo 2^n. Pero, *de manera alternativa*, también puedes usar la otra definición; los ejemplos que se dan efectivamente son para esta segunda definición, ya que algunos valores de c_n se calculan en clase. Traté de no generar confusiones poniendo la definión alternativa entre paréntesis en un párrafo separado; se ve que no lo logré :-( 

El chiste es sólo considerar una de las definiciones, la que quieras, y a partir de ella hacer el cálculo que se pide.

**Comment by Erasmo98** [comment]
Ah, ya quedó claro. Muchas gracias. (:

**Comment by lbenet** [comment]
Cierro el issue...
